# Generated by Django 3.1.3 on 2020-12-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=200)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('price', models.PositiveSmallIntegerField(default=0)),
                ('nights', models.PositiveSmallIntegerField(default=0)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
