# Generated by Django 3.1.3 on 2020-12-06 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_mybooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybooking',
            name='guest',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
