# Generated by Django 3.1.3 on 2020-11-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
