# Generated by Django 3.1.3 on 2020-12-03 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_blog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='num_person',
            field=models.CharField(blank=True, choices=[('1', 'single'), ('2', 'double'), ('family', 'family')], max_length=50),
        ),
        migrations.CreateModel(
            name='RoomDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'available'), ('2', 'unavailable'), ('3', 'checkedIn')], max_length=50)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
        ),
    ]
